### ISSUE TITLE
Error: module `stdlib` is in file 'std\c\stdlib.d' which cannot be read

### ISSUE THREAD

**Issue by andre2007** [NCrashed/daemonize#15]
This import statement causes syntax errors with dmd 2.084.0

https://github.com/NCrashed/daemonize/blob/3c2d0a2cc61f9779b5484a1b71fa374441f0954f/source/daemonize/windows.d#L26

**Comment by NCrashed** [comment]
Hi, could you make PR with tested fix (or test existing PR that I missed) for Windows? I have no chance to test it in Windows for few months, so you help will be really appreciated.

**Comment by andre2007** [comment]
Just saw this pull request will solves the issue

https://github.com/NCrashed/daemonize/pull/14

**Comment by NCrashed** [comment]
Ok, I will make new release with the PR.

**Comment by andre2007** [comment]
Thanks a lot.
I close this issue.
