### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by anton-dutov** [NCrashed/daemonize#6]
Any plans to upgrade compatibility to latest dmd version?
normalize imports, etc.

**Comment by NCrashed** [comment]
I will try to allocate some time for upgrading to the latest dmd version.

**Comment by anton-dutov** [comment]
@NCrashed UP

**Comment by andre2007** [comment]
I can confirm, daemonize now compiles fine on windows and ubuntu linux with dmd 2.084.0.
I thinks this issue can be closed.
